# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\personaldata\Python资料\Python_studyltem\视频转化为图片\myqt\loadwin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QSpacerItem, QSizePolicy


class Ui_loadwin(object):
    def setupUi(self, loadwin):
        loadwin.setObjectName("loadwin")
        # loadwin.resize(455, 349)
        self.gridLayout = QtWidgets.QGridLayout(loadwin)
        self.gridLayout.setObjectName("gridLayout")
        # # 在布局初始化后添加
        # self.gridLayout.setRowStretch(0, 1)  # 图片区域占用剩余空间
        # self.gridLayout.setRowStretch(1, 0)  # 信息标签固定高度
        # self.gridLayout.setRowStretch(2, 0)  # 进度条固定高度
        # self.gridLayout.addItem(
        #     QSpacerItem(0, 10, QSizePolicy.Minimum, QSizePolicy.Fixed), 3, 0
        # )

        self.label_logo = QtWidgets.QLabel(loadwin)
        self.label_logo.setText("")
        self.label_logo.setObjectName("label_logo")

        self.gridLayout.addWidget(self.label_logo, 0, 0, 1, 1)
        self.label_info = QtWidgets.QLabel(loadwin)
        self.label_info.setObjectName("label_info")
        self.gridLayout.addWidget(self.label_info, 1, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(loadwin)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 2, 0, 1, 1)

        self.retranslateUi(loadwin)
        QtCore.QMetaObject.connectSlotsByName(loadwin)

    def retranslateUi(self, loadwin):
        _translate = QtCore.QCoreApplication.translate
        loadwin.setWindowTitle(_translate("loadwin", "Form"))
        self.label_info.setText(_translate("loadwin", "TextLabel"))
