# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\personaldata\Python资料\Python_studyltem\视频转化为图片\myqt\maiwin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainwin(object):
    def setupUi(self, mainwin):
        mainwin.setObjectName("mainwin")
        mainwin.resize(609, 432)
        self.calendarWidget = QtWidgets.QCalendarWidget(mainwin)
        self.calendarWidget.setGeometry(QtCore.QRect(170, 80, 248, 197))
        self.calendarWidget.setObjectName("calendarWidget")
        self.lineEdit = QtWidgets.QLineEdit(mainwin)
        self.lineEdit.setGeometry(QtCore.QRect(180, 320, 231, 21))
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(mainwin)
        QtCore.QMetaObject.connectSlotsByName(mainwin)

    def retranslateUi(self, mainwin):
        _translate = QtCore.QCoreApplication.translate
        mainwin.setWindowTitle(_translate("mainwin", "Form"))

